### ISSUE TITLE
Arithmetic with references

### ISSUE THREAD

**Issue by jedbrown** [Tehforsch/diman#50]
In various circumstances, including with iterators such as below, you're holding a reference and would like to perform arithmetic.
```rs
let velocity = [Velocity::meters_per_second(5.0); 3];
let energy = 0.5 * velocity.iter().map(|v| v * v).sum::<SpecificEnergy>();
```
This works in Diman if one writes the closure as `|v| *v * *v`, but the above works with nondimensional types and is less visually noisy. Should arithmetic (`Add`, `Sub`, `Mul`, `Div`) be implemented for all four combinations in which one or both of the args are references?

Yes, this case also works with `|v| v.powi::<2>()`.

**Comment by Tehforsch** [comment]
This is a good idea. I think anything that works with floats and that we can support should be supported, so I'd like to add this.

**Comment by Tehforsch** [comment]
Done in #53. Your example:
```rust
let velocity = [Velocity::meters_per_second(5.0); 3];
let energy = 0.5 * velocity.iter().map(|v| v * v).sum::<SpecificEnergy>();
```
now compiles.

**Comment by jedbrown** [comment]
Wonderful, thanks!
