### ISSUE TITLE
maintained version of hdf5

### ISSUE THREAD

**Issue by jedbrown** [Tehforsch/diman#78]
The hdf5 lib here has become unmaintained and doesn't work with recent 1.14.x releases. We might want to switch to the [maintained fork](https://github.com/aldanor/hdf5-rust/issues/295).

**Comment by Tehforsch** [comment]
Didn't realize there was a new fork, the lack of 1.14 support had been bothering me for a while (I always kept the `fixed-hdf5-version` branch in this repo pointed at a PR that fixes the issue). I am only worried about the required compiler version - the fork says `1.80` or later is required, which is fairly recent. Then again, this is a nightly-only library anyways, so the amount of people using a pre-`1.80` version is probably low. I will change the dependency to the fork for now.
